#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

CURRENT_DIR=$(pwd)

MAIN_GRAMMAR_NAME="IML"
MAIN_GRAMMAR_RULE="program"
MAIN_GRAMMAR_PATH="$SCRIPT_DIR/src"

SECONDARY_GRAMMAR_NAME="IIML"
SECONDARY_GRAMMAR_RULE="program"
SECONDARY_GRAMMAR_PATH="$SCRIPT_DIR/src/iiml"

FILE_TO_COMPILE=""
OUTPUT_FILE="output.py"

# Get arguments
# Usage:
# ./compile -f fileToCompile
# ./compile -f fileToCompile -o outputFile
while getopts f:o: opts; do
    case ${opts} in
        f) FILE_TO_COMPILE=${OPTARG} ;;
        o) OUTPUT_FILE=${OPTARG} ;;
    esac
done

# Check if the antlr4 tools are installed
COMMANDS_NEEDED=(antlr4 antlr4-test antlr4-build antlr4-run)
for command in "${COMMANDS_NEEDED[@]}"; do
    if ! command -v "$command" &> /dev/null; then
        echo "Command $command not found. Please install the antlr4 tools."
        exit 1
    fi
done

# Build the main grammar
cd "$MAIN_GRAMMAR_PATH"
antlr4-build "$MAIN_GRAMMAR_NAME"

# Build the secondary grammar
cd "$SECONDARY_GRAMMAR_PATH"
antlr4-build -python "$SECONDARY_GRAMMAR_NAME"

# Create a "final" directory
rm -rf "$SCRIPT_DIR/final"
mkdir -p "$SCRIPT_DIR/final"

# Compile the main file
cd "$MAIN_GRAMMAR_PATH"
MAIN_NAME="$MAIN_GRAMMAR_NAME"Main
FILE_PATH=$(basename -- "$FILE_TO_COMPILE")
java "$MAIN_NAME" "$CURRENT_DIR/$FILE_TO_COMPILE" "$SCRIPT_DIR/final/$OUTPUT_FILE"

# Copy the secondary grammar to the final directory
cp "$SECONDARY_GRAMMAR_PATH"/*.py "$SCRIPT_DIR/final"

# Copy images folder to the final directory
if [ -d "$SCRIPT_DIR/src/images" ]; then
    cp -r "$SCRIPT_DIR/src/images" "$SCRIPT_DIR/final"
fi

# Copy helper files to the final directory (if they exist)
if [ -d "$SCRIPT_DIR/helpers" ]; then
    cp "$SCRIPT_DIR/helpers/"* "$SCRIPT_DIR/final"
fi

# Cleanup build files
cd "$MAIN_GRAMMAR_PATH"
antlr4-clean > /dev/null
cd "$SECONDARY_GRAMMAR_PATH"
antlr4-clean -python > /dev/null